# Generated by Django 4.2.17 on 2025-03-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_admin_user_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
