# Generated by Django 4.2.17 on 2025-03-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_remove_admin_password_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='travelrequest',
            old_name='accomodation_id',
            new_name='accomodation',
        ),
        migrations.RenameField(
            model_name='travelrequest',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='travelrequest',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
