# Generated by Django 4.2.17 on 2025-03-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_rename_manager_id_employee_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
