# Generated by Django 4.2.17 on 2025-03-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_travelrequest_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='manager_note',
            field=models.CharField(default='pending', max_length=2000),
        ),
    ]
