# Generated by Django 4.2.17 on 2025-03-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_alter_travelrequest_manager_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_mode',
            field=models.CharField(choices=[('air', 'Air'), ('train', 'Train'), ('car', 'Car'), ('bus', 'Bus')], max_length=30),
        ),
    ]
