# Generated by Django 4.2.17 on 2025-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_travelrequest_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('update', 'Update Requested'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='pending', max_length=20, null=True),
        ),
    ]
