# Generated by Django 4.2.17 on 2025-03-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_travelrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('update', 'Update Requested'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
